### ISSUE TITLE
Missingness

### ISSUE THREAD

**Issue by jotes35** [jaredgk/PPP#19]
Hi,
When I use ppp to phase my data , I get this error
ERROR: 30 individuals with high rates of missing data (>10%). These individuals should be removed. You can disable this error with --force (at your own risk).

Please advice

**Comment by aewebb80** [comment]
Hello. Do you happen to have the pipeline log file for this run (i.e. pipeline.log)?

If not. Which function returned this error? If it was vcf_phase. Which algorithm were you using?

**Comment by jotes35** [comment]
Hi, I used vcf_phase with the shapeit algorithm

**Comment by aewebb80** [comment]
I have update vcf_phase (ae675bc653d9969886787d6b438b758ff1a195ee) with the argument `--shapeit-force` to disable this error.
