### ISSUE TITLE
vcf_filter sample error

### ISSUE THREAD

**Issue by jodyhey** [jaredgk/PPP#20]
running on a model file with a sample individual that is not present generates this error:
Exception: Error: subset called for sample that does not exist in header: "Pan_paniscus-9731_LB502". Use "--force-samples" to ignore this error.

But running with --force-samples does not work

It does not appear that --force-samples is an option with vcf_filter.py

**Comment by aewebb80** [comment]
I have updated vcf_filter (12a81828701f2bcfb011c65b1a16c023ae9b544a) with the argument --force-samples.
