### ISSUE TITLE
reposting genome size file issue

### ISSUE THREAD

**Issue by jodyhey** [jaredgk/PPP#23]
for bed_utilities.py the documentation says
--chrom-file <chrom_filename>
Argument used to define the filename of a file with the sizes of each chromosome file. Appropriate files may be downloaded from the UCSC Genome Browser.

But this does not make clear what the format should be or how to use the genome browser to make the file

(repost - sorry for confusion)

**Comment by aewebb80** [comment]
Added the following text:

Appropriate files may be downloaded from the [UCSC Genome Browser](http://hgdownload.soe.ucsc.edu/downloads.html). The supported **ASSEMBLY.chrom.sizes** file for each assembly may be found by clicking **Genome sequence files and select annotations** (followed by **Standard genome sequence files and select annotations on select assemblies**).

**Comment by jodyhey** [comment]
I'm still lost.   Are you in downloads?  Table browser?   do you have the actual link for hg18 ? 

thanks

**Comment by jodyhey** [comment]
got it
http://hgdownload.cse.ucsc.edu/goldenpath/hg18/bigZips/hg18.chrom.sizes
