### ISSUE TITLE
informative_loci_filter errors  

### ISSUE THREAD

**Issue by jodyhey** [jaredgk/PPP#24]
I tried running informative_loci_filter.py  which returned an error ("ValueError: fetch requires an index")

Here is the command and return:

informative_loci_filter.py --vcf 2Pop.TV.Filtered.vcf.gz --bed hg18_subset_intersects.genes_and_RM_subtracted.bed --remove-indels --minsites 4 --keep-full-line --out hg18_subset_informative.genes_and_RM_subtracted.bed
exp_handler - ERROR: fetch requires an index
Traceback (most recent call last):
  File "/home/jodyhey/anaconda3/envs/py-popgen/bin/informative_loci_filter.py", line 260, in <module>
    filter_bed_regions(sys.argv[1:])
  File "/home/jodyhey/anaconda3/envs/py-popgen/bin/informative_loci_filter.py", line 231, in filter_bed_regions
    rec_list = vcf_reader.getRecordList(region)
  File "/home/jodyhey/anaconda3/envs/py-popgen/lib/python3.7/site-packages/pgpipe/vcf_reader_func.py", line 405, in getRecordList
    return getRecordList(self.reader, region, chrom, start, end, self.chr_in_chrom)
  File "/home/jodyhey/anaconda3/envs/py-popgen/lib/python3.7/site-packages/pgpipe/vcf_reader_func.py", line 516, in getRecordList
    var_sites = vcf_reader.fetch(c, region.start, region.end)
  File "pysam/libcbcf.pyx", line 4370, in pysam.libcbcf.VariantFile.fetch
ValueError: fetch requires an index

So I tried tabixing the vcf 

 tabix -p vcf 2Pop.TV.Filtered.vcf.gz

I then reran the command and got a pysam error ("ValueError: start out of range (-1)")

Here is the command and return

informative_loci_filter.py --vcf 2Pop.TV.Filtered.vcf.gz --bed hg18_subset_intersects.genes_and_RM_subtracted.bed --remove-indels --minsites 4 --keep-full-line --out hg18_subset_informative.genes_and_RM_subtracted.bed

exp_handler - ERROR: start out of range (-1)
Traceback (most recent call last):
  File "/home/jodyhey/anaconda3/envs/py-popgen/bin/informative_loci_filter.py", line 260, in <module>
    filter_bed_regions(sys.argv[1:])
  File "/home/jodyhey/anaconda3/envs/py-popgen/bin/informative_loci_filter.py", line 231, in filter_bed_regions
    rec_list = vcf_reader.getRecordList(region)
  File "/home/jodyhey/anaconda3/envs/py-popgen/lib/python3.7/site-packages/pgpipe/vcf_reader_func.py", line 405, in getRecordList
    return getRecordList(self.reader, region, chrom, start, end, self.chr_in_chrom)
  File "/home/jodyhey/anaconda3/envs/py-popgen/lib/python3.7/site-packages/pgpipe/vcf_reader_func.py", line 516, in getRecordList
    var_sites = vcf_reader.fetch(c, region.start, region.end)
  File "pysam/libcbcf.pyx", line 4372, in pysam.libcbcf.VariantFile.fetch
  File "pysam/libchtslib.pyx", line 691, in pysam.libchtslib.HTSFile.parse_region
ValueError: start out of range (-1)

**Comment by jodyhey** [comment]
I also tried tabix with -0
tabix -0 -p vcf 2Pop.TV.Filtered.vcf.gz

but I still gotthe same error
ValueError: start out of range (-1)

**Comment by aewebb80** [comment]
Can you email/link  hg18_subset_intersects.genes_and_RM_subtracted.bed?

**Comment by aewebb80** [comment]
It appears the error occurs when a start value in a BED is equal to 0.

**Comment by aewebb80** [comment]
I'm also curious why our BED files would be different. Since the min start value in my file was 1000

**Comment by aewebb80** [comment]
@jaredgk. While I was looking in the code I noticed it has options for zero-based files. Do we need to specify an argument to avoid this error? And if so. Should that be the default if a BED file is used?

**Comment by aewebb80** [comment]
> I'm also curious why our BED files would be different. Since the min start value in my file was 1000

Found what may have caused it: 

`bed_utilities.py --utility intersect --bed hg18_windows.genes_subtracted.bed --intersect-file 2Pop.TV.Filtered_Subset.vcf.gz --out hg18_subset_intersects.genes_and_RM_subtracted.bed`

should have been:

`bed_utilities.py --utility intersect --bed hg18_windows.genes_and_RM_subtracted.bed --intersect-file 2Pop.TV.Filtered_Subset.vcf.gz --out hg18_subset_intersects.genes_and_RM_subtracted.bed`

**Comment by aewebb80** [comment]
I think our RepeatMasker files are different,

**Comment by jodyhey** [comment]
so a couple of issues here:
-should tabix be run on the vcf with -0 or not?
- should I be building hg18_RM.bed differently?  I just checked 'RepeatMasker' track,  'Variation and Repeats" and BED under Hg18
- the following seemed to run ok
bed_utilities.py --utility intersect --bed  hg18_windows.genes_and_RM_subtracted.bed --intersect-file 2Pop.TV.Filtered.vcf.gz --out hg18_subset_intersects.genes_and_RM_subtracted.bed

**Comment by jodyhey** [comment]
this just seemed to run ok

informative_loci_filter.py --vcf 2Pop.TV.Filtered.vcf.gz --bed  hg18_subset_intersects.genes_and_RM_subtracted.bed --remove-indels --minsites 4 --keep-full-line --out hg18_subset_informative.genes_and_RM_subtracted.bed

**Comment by aewebb80** [comment]
I would just do `tabix -p vcf` as the VCF should not be zero based. 

However, the original error only show's up with a BED start site of 0. Which appears to be converted to -1.

So I'm curious if the other sizes are also being converted. So:

```
   0-1000
1000-2000
2000-3000
```

becomes:
```
  -1-1000
 999-2000
1999-3000
```

**Comment by aewebb80** [comment]
Looks like using the option: `--zero-ho` resolves the original error. Which makes me thing the command should be:

informative_loci_filter.py --vcf 2Pop.TV.Filtered_Subset.vcf.gz --bed hg18_subset_intersects.genes_and_RM_subtracted.bed --remove-indels --minsites 4 --keep-full-line --out hg18_subset_informative.genes_and_RM_subtracted.bed --zero-ho

**Comment by aewebb80** [comment]
@jaredgk Can you confirm that we need to use this option when using a BED file.

**Comment by jodyhey** [comment]
I'm going to close this,  I think my original bed files was wrong
