### ISSUE TITLE
vcf_split directory creation error

### ISSUE THREAD

**Issue by jodyhey** [jaredgk/PPP#28]
this command 
vcf_split.py --vcf 2Pop.TV.Filtered.vcf.gz --split-method bed --split-file hg18_sampled.genes_and_RM_subtracted.bed --out-dir 2Pop_TV_sampled --out-prefix 2Pop.TV

triggered this error
  raise IOError('%s already exists' % vcf_args.out_dir)
OSError: 2Pop_TV_sampled already exists

seems like this could be trapped

**Comment by aewebb80** [comment]
This is an intended exception to prevent overwriting previous work and can be ignored using `--overwrite`.

I can update the text to make this more obvious.
