### ISSUE TITLE
informative_loci_filter is skipping all chromosomes but the first

### ISSUE THREAD

**Issue by jodyhey** [jaredgk/PPP#30]
informative_loci_filter is giving me a bed file with only regions from the first chromosome in the filter bed and vcf

I think the problem has to do with use of prev_last_rec in getRecordListUnzipped() in vcf_reader_func
from line 565
    if (prev_last_rec is not None and
        region.containsRecord(prev_last_rec) == 'in'):
        lst.append(prev_last_rec)
    elif (prev_last_rec is not None and
         region.containsRecord(prev_last_rec) == 'after'):
        return [],prev_last_rec  #jh added ',prev_last_rec'  6/5/2020

When this is called with a region that is not on the same chromosome as was prev_last_rec   it returns an empty list  ??

And this causes all regions on all chromosomes but the first to be skipped .   
(also  I can't get informative_loci_filter to run a .vcf.gz file - next issue)

**Comment by jodyhey** [comment]
should lines 569-570 in vcf_reader_func be deleted ?   This fixes my current problem.

**Comment by jaredgk** [comment]
I think this is actually a bug from a different area- I inadvertently flipped the chromosome comparison in genome_region so that chr12 < chr11. I'll fix it in my next push. But the lines 569-570 should be kept.

**Comment by jaredgk** [comment]
Bug in genome_region has been fixed, so this issue should no longer present itself.
