### ISSUE TITLE
Combining files for many populations

### ISSUE THREAD

**Issue by allisoncoomber** [jaredgk/PPP#41]
Hi,

I am following along with the example workflow in the Jupyter notebook using some experimental data I have, but I am confused on when and where to combine files. The example has a 2 population model file, but I am working with 7 populations. Running vcf_calc on my 7Pop model is successful but returns 21 files (seems to be pairwise comparisons of my 7 populations). Is there a way to combine these before filtering for informative loci? Or should I be combining things somewhere downstream? My goal is to eventually analyze all 7 populations with IMa3.

Apologies if this is not the correct place to ask - I was unable to access the google group in the documentation.

Thanks,
Allison

**Comment by jodyhey** [comment]
That pipeline is demonstrating ways to measure things about your data should you wish to make sure that the loci used for IMA3 include parts of the genome that show particularly properties.  (e.g. based on Fst values). 

you could certainly summarize the outputs of those 21 files (using something other than PPP) to select loci. 

You could also not filter loci,  which is often preferable,  as filtering can introduce biases. 

Jody
