### ISSUE TITLE
High Tajima's D value

### ISSUE THREAD

**Issue by atoselan** [jaredgk/PPP#42]
Hi, it may be a silly question but how is the number of snps calculated for Tajima's D? I only ask because I have a multi-sample vcf file and I've calculated Tajima's D across 10kb windows and for the majority of bins, D is >2 which seems unlikely. I assume that 'number of sites' is the number of heterozygous positions per bin, but I would like to check how n_snps is calculated as it is either identical or nearly identical for nearly all bins. The organism I'm working on is diploid, average coverage is fairly low (~30x), I have 5 replicates and I get the same results with vcftools tajimaD.

Cheers,
Andrew

**Comment by jodyhey** [comment]
It is odd to have such high D values.   The number of snps would typically be the number of rows in the vcf file for the region that describe a snp variant.   D also depends on a pairwise measure,  nucleotide diversity (see https://en.wikipedia.org/wiki/Tajima%27s_D).   If you feel pretty sure there is a bug, please post a portion of the VCF file that triggers the problem.

**Comment by atoselan** [comment]
Thanks for your reply. I'm not sure I understand the difference in the output then between n_sites and n_snps. If n_sites is the number of segregating sites, is that not also the number of rows for that region that describe a snp? Apologies if I'm being slow, might be the heatwave we're having...

**Comment by atoselan** [comment]
Hi,

Here's a snippet of the vcf file that's giving me strange results. I don't think it's a bug with vcf-kit as I get pretty much the same results with vcftools.

Many thanks,
Andrew


##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##samtoolsVersion=1.11+htslib-1.11
##samtoolsCommand=samtools mpileup -t DP,AD -Buf /gpfs/data/mock_lab/andrew-temp/reference_genomes/T_pseudonana/Thaps3_chromosomes_assembly_repeatmasked.fasta /gp             fs/home/bva09npu/scratch/WGS/SAM37199/SAM37199.tmp.bam
##reference=file:///gpfs/data/mock_lab/andrew-temp/reference_genomes/T_pseudonana/Thaps3_chromosomes_assembly_repeatmasked.fasta
##contig=<ID=chr_1,length=3042585>
##contig=<ID=chr_2,length=2707195>
##contig=<ID=chr_3,length=2440052>
##contig=<ID=chr_4,length=2402323>
##contig=<ID=chr_5,length=2305972>
##contig=<ID=chr_6,length=2071480>
##contig=<ID=chr_7,length=1992434>
##contig=<ID=chr_8,length=1267198>
##contig=<ID=chr_9,length=1191060>
##contig=<ID=chr_10,length=1105668>
##contig=<ID=chr_11a,length=806142>
##contig=<ID=chr_11b,length=82843>
##contig=<ID=chr_12,length=1128382>
##contig=<ID=chr_13,length=1052196>
##contig=<ID=chr_14,length=998643>
##contig=<ID=chr_15,length=931268>
##contig=<ID=chr_16a,length=459776>
##contig=<ID=chr_16b,length=169376>
##contig=<ID=chr_17,length=659924>
##contig=<ID=chr_18,length=827053>
##contig=<ID=chr_19a_19,length=607239>
##contig=<ID=chr_19b_31,length=151677>
##contig=<ID=chr_19c_29,length=291194>
##contig=<ID=chr_20,length=800234>
##contig=<ID=chr_22,length=1057565>
##contig=<ID=chr_23,length=454954>
##contig=<ID=chr_24,length=297349>
##ALT=<ID=*,Description="Represents allele(s) other than observed.">
##INFO=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">
##INFO=<ID=IDV,Number=1,Type=Integer,Description="Maximum number of reads supporting an indel">
##INFO=<ID=IMF,Number=1,Type=Float,Description="Maximum fraction of reads supporting an indel">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Raw read depth">
##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">
##INFO=<ID=RPB,Number=1,Type=Float,Description="Mann-Whitney U test of Read Position Bias (bigger is better)">
##INFO=<ID=MQB,Number=1,Type=Float,Description="Mann-Whitney U test of Mapping Quality Bias (bigger is better)">
##INFO=<ID=BQB,Number=1,Type=Float,Description="Mann-Whitney U test of Base Quality Bias (bigger is better)">
##INFO=<ID=MQSB,Number=1,Type=Float,Description="Mann-Whitney U test of Mapping Quality vs Strand Bias (bigger is better)">
##INFO=<ID=SGB,Number=1,Type=Float,Description="Segregation based metric.">
##INFO=<ID=MQ0F,Number=1,Type=Float,Description="Fraction of MQ0 reads (smaller is better)">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="List of Phred-scaled genotype likelihoods">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Number of high-quality bases">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=ICB,Number=1,Type=Float,Description="Inbreeding Coefficient Binomial test (bigger is better)">
##INFO=<ID=HOB,Number=1,Type=Float,Description="Bias in the number of HOMs number (smaller is better)">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=DP4,Number=4,Type=Integer,Description="Number of high-quality ref-forward , ref-reverse, alt-forward and alt-reverse bases">
##INFO=<ID=MQ,Number=1,Type=Integer,Description="Average mapping quality">
##bcftools_callVersion=1.10.2+htslib-1.10.2
##bcftools_callCommand=call --threads 8 -m -Ob -o /gpfs/home/bva09npu/scratch/WGS/SAM37199/SAM37199.call.bcf; Date=Tue Jul 19 10:24:58 2022
##FILTER=<ID=SnpGap,Description="SNP within 10 bp of an indel">
##bcftools_filterVersion=1.10.2+htslib-1.10.2
##bcftools_filterCommand=filter --SnpGap 10 --include 'MQ>=40 & %QUAL>40 & FMT/DP>=10 & FMT/DP<=2*23.6802' -Ob -o /gpfs/home/bva09npu/scratch/WGS/SAM37199/SAM3719             9.filtered_V2.bcf /gpfs/home/bva09npu/scratch/WGS/SAM37199/SAM37199.call.bcf; Date=Tue Jul 19 10:31:26 2022
##bcftools_mergeVersion=1.10.2+htslib-1.10.2
##bcftools_mergeCommand=merge --threads 15 --merge all -Ov SAM37199/SAM37199.filtered_V2.bcf SAM37200/SAM37200.filtered_V2.bcf SAM37201/SAM37201.filtered_V2.bcf S             AM37202/SAM37202.filtered_V2.bcf SAM37203/SAM37203.filtered_V2.bcf; Date=Tue Jul 19 14:15:54 2022
##bcftools_filterCommand=filter -Ov -; Date=Tue Jul 19 14:15:54 2022
##bcftools_viewVersion=1.10.2+htslib-1.10.2
##bcftools_viewCommand=view -v snps -Ob -o merged_T50_32C_V2.bcf -; Date=Tue Jul 19 14:15:54 2022
##bcftools_viewCommand=view -r chr_15:0-5000 -Ov merged_T50_32C_V2.bcf; Date=Tue Jul 19 15:29:34 2022
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAM37199        SAM37200        SAM37201        SAM37202        SAM37203
chr_15  483     .       G       A       222     PASS    VDB=0.399768;SGB=-0.683931;RPB=0.730706;MQB=1;MQSB=1;BQB=0.741321;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=160;DP4=41             ,29,43,28;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,255:33:20,13  0/1:255,0,255:42:17,25  0/1:244,0,165:16:6,10   0/1:255,0,255:28:16,12  0/1:246,0,255:22:11,11
chr_15  1019    .       C       G       222     PASS    VDB=0.241431;SGB=-0.683931;RPB=0.667426;MQB=1;MQSB=1;BQB=0.272532;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=122;DP4=24             ,34,28,25;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,228:23:10,13  0/1:255,0,255:30:14,16  0/1:129,0,255:19:13,6   0/1:253,0,255:22:11,11  0/1:149,0,242:17:10,7
chr_15  1515    .       T       C       222     PASS    VDB=0.0621896;SGB=-0.686358;RPB=0.797149;MQB=1;MQSB=1;BQB=0.870352;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=144;DP4=3             4,31,27,45;AN=10;AC=5   GT:PL:DP:AD     0/1:255,0,221:24:10,14  0/1:255,0,255:36:17,19  0/1:255,0,255:36:21,15  0/1:255,0,135:19:6,13   0/1:189,0,239:22:11,11
chr_15  1688    .       T       C       222     PASS    VDB=0.598255;SGB=-0.662043;RPB=0.934777;MQB=1;MQSB=1;BQB=0.851213;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=136;DP4=36             ,34,39,20;AN=10;AC=5    GT:PL:DP:AD     0/1:213,0,255:22:13,9   0/1:255,0,255:30:15,15  0/1:255,0,255:34:18,16  0/1:255,0,175:21:8,13   0/1:130,0,255:22:16,6
chr_15  1869    .       T       C       222     PASS    VDB=0.0243482;SGB=-0.636426;RPB=0.621145;MQB=1;MQSB=1;BQB=0.273507;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=146;DP4=3             0,40,28,34;AN=10;AC=5   GT:PL:DP:AD     0/1:205,0,244:17:10,7   0/1:255,0,255:37:23,14  0/1:255,0,255:32:15,17  0/1:255,0,255:30:15,15  0/1:255,0,161:16:7,9
chr_15  1870    .       C       T       222     PASS    VDB=0.0247636;SGB=-0.636426;RPB=0.591555;MQB=1;MQSB=1;BQB=0.981133;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=148;DP4=3             1,40,29,33;AN=10;AC=5   GT:PL:DP:AD     0/1:194,0,255:17:10,7   0/1:255,0,255:39:23,16  0/1:255,0,255:32:15,17  0/1:255,0,255:29:16,13  0/1:255,0,167:16:7,9
chr_15  2085    .       G       A       222     PASS    VDB=0.959399;SGB=-0.683931;RPB=0.988235;MQB=1;MQSB=1;BQB=0.48376;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=129;DP4=31,             32,21,30;AN=10;AC=5     GT:PL:DP:AD     0/1:255,0,255:26:13,13  0/1:255,0,255:31:17,14  0/1:139,0,255:17:12,5   0/1:115,0,255:16:11,5   0/1:255,0,234:24:10,14
chr_15  2124    .       G       T       222     PASS    VDB=0.286863;SGB=-0.670168;RPB=0.936355;MQB=1;MQSB=1;BQB=0.999457;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=109;DP4=24             ,34,18,26;AN=10;AC=5    GT:PL:DP:AD     0/1:239,0,255:22:12,10  0/1:255,0,255:29:15,14  0/1:150,0,235:16:11,5   0/1:88,0,208:15:11,4    0/1:251,0,225:20:9,11
chr_15  2131    .       G       A       222     PASS    VDB=0.511287;SGB=-0.680642;RPB=0.547898;MQB=1;MQSB=1;BQB=0.704395;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=116;DP4=23             ,35,22,27;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,255:24:12,12  0/1:255,0,255:31:15,16  0/1:177,0,255:18:12,6   0/1:100,0,207:16:11,5   0/1:225,0,198:18:8,10
chr_15  2139    .       A       G       222     PASS    VDB=0.527393;SGB=-0.680642;RPB=0.569783;MQB=1;MQSB=1;BQB=0.963693;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=117;DP4=24             ,37,20,28;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,255:25:13,12  0/1:255,0,255:31:16,15  0/1:174,0,255:19:13,6   0/1:105,0,201:16:11,5   0/1:229,0,207:18:8,10
chr_15  2154    .       A       T       222     PASS    VDB=0.187503;SGB=-0.670168;RPB=0.704349;MQB=1;MQSB=1;BQB=0.969699;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=115;DP4=21             ,38,21,27;AN=10;AC=5    GT:PL:DP:AD     0/1:236,0,255:23:13,10  0/1:255,0,255:30:17,13  0/1:208,0,255:20:12,8   0/1:176,0,205:19:11,8   0/1:219,0,161:15:6,9
chr_15  2159    .       A       T       222     PASS    VDB=0.181735;SGB=-0.670168;RPB=0.667426;MQB=1;MQSB=1;BQB=0.921963;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=119;DP4=21             ,41,21,27;AN=10;AC=5    GT:PL:DP:AD     0/1:237,0,255:23:13,10  0/1:255,0,255:30:17,13  0/1:200,0,255:22:14,8   0/1:188,0,233:20:12,8   0/1:222,0,183:15:6,9
chr_15  2261    .       A       T       222     PASS    VDB=0.855481;SGB=-0.670168;RPB=0.948436;MQB=1;MQSB=1;BQB=0.588086;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=110;DP4=22             ,29,31,21;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,139:16:6,10   0/1:255,0,240:25:11,14  0/1:255,0,255:29:14,15  0/1:209,0,216:16:8,8    0/1:105,0,255:17:12,5
chr_15  2353    .       G       A       222     PASS    VDB=0.879559;SGB=-0.662043;RPB=0.987474;MQB=1;MQSB=1;BQB=0.759945;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=109;DP4=36             ,16,35,17;AN=10;AC=5    GT:PL:DP:AD     0/1:218,0,180:16:7,9    0/1:233,0,255:20:11,9   0/1:255,0,228:24:10,14  0/1:241,0,255:26:14,12  0/1:191,0,248:18:10,8
chr_15  2364    .       T       C       222     PASS    VDB=0.965099;SGB=-0.662043;RPB=0.989637;MQB=1;MQSB=1;BQB=0.981652;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=110;DP4=36             ,14,37,18;AN=10;AC=5    GT:PL:DP:AD     0/1:219,0,187:17:8,9    0/1:255,0,244:22:10,12  0/1:255,0,204:22:9,13   0/1:246,0,255:28:15,13  0/1:195,0,226:16:8,8
chr_15  2500    .       A       G       222     PASS    VDB=0.454779;SGB=-0.686358;RPB=0.679965;MQB=1;MQSB=1;BQB=0.357364;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=132;DP4=27             ,30,33,34;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,224:24:10,14  0/1:255,0,255:31:13,18  0/1:255,0,255:27:12,15  0/1:234,0,219:21:11,10  0/1:255,0,229:21:11,10
chr_15  3797    .       G       T       222     PASS    VDB=0.941134;SGB=-0.686358;RPB=0.90913;MQB=1;MQSB=1;BQB=1;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=140;DP4=35,29,31,3             2;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,255:28:14,14  0/1:255,0,255:29:16,13  0/1:255,0,249:24:10,14  0/1:185,0,255:19:12,7   0/1:255,0,255:27:12,15
chr_15  3880    .       C       T       222     PASS    VDB=0.874637;SGB=-0.686358;RPB=0.947681;MQB=1;MQSB=1;BQB=0.980132;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=152;DP4=34             ,38,37,35;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,255:33:19,14  0/1:255,0,255:30:15,15  0/1:255,0,255:32:17,15  0/1:255,0,238:21:10,11  0/1:255,0,255:28:11,17
chr_15  3917    .       A       G       222     PASS    VDB=0.570811;SGB=-0.686358;RPB=0.990971;MQB=1;MQSB=1;BQB=0.620793;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=159;DP4=38             ,42,41,31;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,255:35:21,14  0/1:255,0,255:40:19,21  0/1:255,0,255:28:17,11  0/1:224,0,255:21:12,9   0/1:255,0,255:28:11,17
chr_15  4002    .       G       A       222     PASS    VDB=0.617917;SGB=-0.683931;RPB=0.988053;MQB=1;MQSB=1;BQB=0.933111;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=153;DP4=42             ,32,46,23;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,250:23:10,13  0/1:255,0,255:39:19,20  0/1:253,0,255:35:22,13  0/1:194,0,255:18:11,7   0/1:255,0,239:28:12,16
chr_15  4215    .       T       A       222     PASS    VDB=0.886762;SGB=-0.689466;RPB=0.706724;MQB=1;MQSB=1;BQB=0.976248;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=150;DP4=32             ,40,35,35;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,245:29:13,16  0/1:255,0,255:47:28,19  0/1:255,0,255:32:16,16  0/1:255,0,187:18:8,10   0/1:230,0,181:16:7,9
chr_15  4304    .       T       A       222     PASS    VDB=0.147748;SGB=-0.688148;RPB=0.958048;MQB=1;MQSB=1;BQB=0.273507;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=159;DP4=35             ,35,47,30;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,255:27:12,15  0/1:255,0,255:39:18,21  0/1:255,0,255:34:17,17  0/1:255,0,204:20:9,11   0/1:255,0,255:27:14,13
chr_15  4330    .       C       G       222     PASS    VDB=0.0711402;SGB=-0.686358;RPB=0.20916;MQB=1;MQSB=1;BQB=0.934673;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=147;DP4=32             ,38,38,30;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,255:28:14,14  0/1:255,0,255:37:19,18  0/1:255,0,255:28:14,14  0/1:234,0,174:17:8,9    0/1:255,0,255:28:15,13
chr_15  4568    .       A       T       222     PASS    VDB=0.953007;SGB=-0.670168;RPB=0.817757;MQB=1;MQSB=1;BQB=0.943335;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=132;DP4=34             ,24,31,35;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,178:17:7,10   0/1:255,0,255:35:15,20  0/1:255,0,255:33:17,16  0/1:254,0,189:19:8,11   0/1:244,0,255:20:11,9
chr_15  4596    .       T       C       222     PASS    VDB=0.82322;SGB=-0.680642;RPB=0.818731;MQB=1;MQSB=1;BQB=0.951229;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=141;DP4=32,             24,36,37;AN=10;AC=5     GT:PL:DP:AD     0/1:255,0,128:17:5,12   0/1:255,0,255:41:19,22  0/1:255,0,255:31:15,16  0/1:255,0,170:19:7,12   0/1:255,0,255:21:10,11
chr_15  4645    .       C       A       222     PASS    VDB=0.484415;SGB=-0.680642;RPB=0.998108;MQB=1;MQSB=1;BQB=0.842882;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=137;DP4=34             ,25,32,37;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,255:23:11,12  0/1:255,0,255:41:22,19  0/1:255,0,253:23:11,12  0/1:255,0,105:20:5,15   0/1:250,0,252:21:10,11
chr_15  4670    .       A       C       222     PASS    VDB=0.328032;SGB=-0.662043;RPB=0.77073;MQB=1;MQSB=1;BQB=0.981652;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=120;DP4=27,             25,32,28;AN=10;AC=5     GT:PL:DP:AD     0/1:227,0,203:17:8,9    0/1:255,0,255:41:22,19  0/1:242,0,237:20:10,10  0/1:255,0,63:17:3,14    0/1:215,0,240:17:9,8
chr_15  4757    .       T       G       222     PASS    VDB=0.887186;SGB=-0.670168;RPB=0.991158;MQB=1;MQSB=1;BQB=0.824135;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=99;DP4=20,             25,22,25;AN=8;AC=4      GT:PL:DP:AD     0/1:244,0,221:18:8,10   0/1:255,0,255:34:19,15  0/1:245,0,234:23:12,11  0/1:255,0,159:17:6,11   ./.:.:.:.
chr_15  4818    .       C       A       222     PASS    VDB=0.896381;SGB=-0.680642;RPB=0.802184;MQB=1;MQSB=1;BQB=0.91051;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=129;DP4=29,             33,34,25;AN=10;AC=5     GT:PL:DP:AD     0/1:255,0,255:24:12,12  0/1:255,0,255:37:24,13  0/1:255,0,242:24:12,12  0/1:255,0,150:22:6,16   0/1:160,0,227:14:8,6
chr_15  4832    .       T       A       222     PASS    VDB=0.71014;SGB=-0.680642;RPB=0.994334;MQB=1;MQSB=1;BQB=0.977529;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=131;DP4=32,             30,33,29;AN=10;AC=5     GT:PL:DP:AD     0/1:255,0,217:21:9,12   0/1:255,0,255:38:23,15  0/1:255,0,255:24:13,11  0/1:255,0,151:24:7,17   0/1:173,0,255:17:10,7
chr_15  4843    .       C       T       222     PASS    VDB=0.424843;SGB=-0.676189;RPB=0.927743;MQB=1;MQSB=1;BQB=0.927743;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=129;DP4=30             ,27,38,24;AN=10;AC=5    GT:PL:DP:AD     0/1:255,0,239:21:10,11  0/1:255,0,255:37:21,16  0/1:255,0,251:23:11,12  0/1:255,0,111:21:5,16   0/1:158,0,255:17:10,7
chr_15  4945    .       A       C       222     PASS    VDB=0.633718;SGB=-0.662043;RPB=0.203896;MQB=1;MQSB=1;BQB=0.809014;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=135;DP4=41             ,20,31,28;AN=10;AC=5    GT:PL:DP:AD     0/1:247,0,255:25:16,9   0/1:255,0,255:35:21,14  0/1:230,0,158:19:9,10   0/1:255,0,113:21:5,16   0/1:243,0,233:20:10,10
chr_15  4954    .       C       G       222     PASS    VDB=0.635556;SGB=-0.662043;RPB=0.168768;MQB=1;MQSB=1;BQB=0.999637;MQ0F=0;ICB=1;HOB=0.5;MQ=60;DP=140;DP4=43             ,23,30,29;AN=10;AC=5    GT:PL:DP:AD     0/1:237,0,255:26:17,9   0/1:255,0,255:40:25,15  0/1:218,0,249:21:12,9   0/1:255,0,60:19:3,16    0/1:242,0,229:19:9,10

**Comment by jodyhey** [comment]
Yeah so each individual at each SNP is heterozygous in those data,  so that would make Tajima's D go thru the roof. 

If that is typical of your data,  then something is weird and Taj D maybe the least of your issues

**Comment by atoselan** [comment]
Ok, thanks. I'll do some more digging into the alignments and see if anything weird stands out.
